"""initial schema

Revision ID: 5b1f15468b13
Revises: 
Create Date: 2026-06-25 12:04:33.225906
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b1f15468b13'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expense_categories'))
    )
    op.create_index(op.f('ix_expense_categories_deleted_at'), 'expense_categories', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expense_categories_slug'), 'expense_categories', ['slug'], unique=True)
    op.create_index(op.f('ix_expense_categories_status'), 'expense_categories', ['status'], unique=False)
    op.create_index(op.f('ix_expense_categories_uuid'), 'expense_categories', ['uuid'], unique=True)
    op.create_table('groups',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_index(op.f('ix_groups_deleted_at'), 'groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=True)
    op.create_index(op.f('ix_groups_status'), 'groups', ['status'], unique=False)
    op.create_index(op.f('ix_groups_uuid'), 'groups', ['uuid'], unique=True)
    op.create_table('permissions',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index(op.f('ix_permissions_deleted_at'), 'permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('ix_permissions_slug'), 'permissions', ['slug'], unique=True)
    op.create_index(op.f('ix_permissions_status'), 'permissions', ['status'], unique=False)
    op.create_index(op.f('ix_permissions_uuid'), 'permissions', ['uuid'], unique=True)
    op.create_table('settings',
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.Enum('string', 'number', 'boolean', 'json', name='settingtype', native_enum=False, length=20), nullable=False),
    sa.Column('group_name', sa.String(length=80), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_settings'))
    )
    op.create_index(op.f('ix_settings_group_name'), 'settings', ['group_name'], unique=False)
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.create_index(op.f('ix_settings_uuid'), 'settings', ['uuid'], unique=True)
    op.create_table('suppliers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppliers'))
    )
    op.create_index(op.f('ix_suppliers_deleted_at'), 'suppliers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_index(op.f('ix_suppliers_uuid'), 'suppliers', ['uuid'], unique=True)
    op.create_table('users',
    sa.Column('lastname', sa.String(length=120), nullable=False),
    sa.Column('firstname', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('avatar', sa.String(length=512), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('is_activated', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', 'invited', name='userstatus', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=False)
    op.create_index(op.f('ix_users_status'), 'users', ['status'], unique=False)
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_table('activity_logs',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=150), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=True),
    sa.Column('reference_type', sa.Enum('COMMANDE', 'VENTE', 'PURCHASE', 'PAIEMENT', 'CREANCE', 'AJUSTEMENT', 'INVENTAIRE', 'EXPENSE', 'CASH_SESSION', 'PRODUCT', 'STORE', 'USER', name='referencetype', native_enum=False, length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_activity_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_logs'))
    )
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_module'), 'activity_logs', ['module'], unique=False)
    op.create_index(op.f('ix_activity_logs_user_id'), 'activity_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_uuid'), 'activity_logs', ['uuid'], unique=True)
    op.create_table('attachments',
    sa.Column('reference_type', sa.Enum('COMMANDE', 'VENTE', 'PURCHASE', 'PAIEMENT', 'CREANCE', 'AJUSTEMENT', 'INVENTAIRE', 'EXPENSE', 'CASH_SESSION', 'PRODUCT', 'STORE', 'USER', name='referencetype', native_enum=False, length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('file_url', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=80), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_attachments_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    op.create_index(op.f('ix_attachments_reference_id'), 'attachments', ['reference_id'], unique=False)
    op.create_index(op.f('ix_attachments_reference_type'), 'attachments', ['reference_type'], unique=False)
    op.create_index(op.f('ix_attachments_uuid'), 'attachments', ['uuid'], unique=True)
    op.create_table('category_products',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_category_products_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_products'))
    )
    op.create_index(op.f('ix_category_products_deleted_at'), 'category_products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_category_products_slug'), 'category_products', ['slug'], unique=True)
    op.create_index(op.f('ix_category_products_status'), 'category_products', ['status'], unique=False)
    op.create_index(op.f('ix_category_products_uuid'), 'category_products', ['uuid'], unique=True)
    op.create_table('category_stores',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_category_stores_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_category_stores'))
    )
    op.create_index(op.f('ix_category_stores_deleted_at'), 'category_stores', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_category_stores_slug'), 'category_stores', ['slug'], unique=True)
    op.create_index(op.f('ix_category_stores_status'), 'category_stores', ['status'], unique=False)
    op.create_index(op.f('ix_category_stores_uuid'), 'category_stores', ['uuid'], unique=True)
    op.create_table('group_permissions',
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_permissions_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_group_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_permissions'))
    )
    op.create_index(op.f('ix_group_permissions_deleted_at'), 'group_permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_group_permissions_group_id'), 'group_permissions', ['group_id'], unique=False)
    op.create_index(op.f('ix_group_permissions_permission_id'), 'group_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_group_permissions_status'), 'group_permissions', ['status'], unique=False)
    op.create_index(op.f('ix_group_permissions_uuid'), 'group_permissions', ['uuid'], unique=True)
    op.create_table('notifications',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('stock', 'commande', 'vente', 'creance', 'paiement', 'systeme', name='notificationtype', native_enum=False, length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_uuid'), 'notifications', ['uuid'], unique=True)
    op.create_table('purchases',
    sa.Column('supplier_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('brouillon', 'commandee', 'partiellement_recue', 'recue', 'annulee', name='purchasestatut', native_enum=False, length=25), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_purchases_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_purchases_supplier_id_suppliers'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchases'))
    )
    op.create_index(op.f('ix_purchases_deleted_at'), 'purchases', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_purchases_status'), 'purchases', ['status'], unique=False)
    op.create_index(op.f('ix_purchases_statut'), 'purchases', ['statut'], unique=False)
    op.create_index(op.f('ix_purchases_supplier_id'), 'purchases', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchases_uuid'), 'purchases', ['uuid'], unique=True)
    op.create_table('roles',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_roles_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles'))
    )
    op.create_index(op.f('ix_roles_deleted_at'), 'roles', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=True)
    op.create_index(op.f('ix_roles_status'), 'roles', ['status'], unique=False)
    op.create_index(op.f('ix_roles_uuid'), 'roles', ['uuid'], unique=True)
    op.create_table('user_groups',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_user_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_groups'))
    )
    op.create_index(op.f('ix_user_groups_deleted_at'), 'user_groups', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_groups_group_id'), 'user_groups', ['group_id'], unique=False)
    op.create_index(op.f('ix_user_groups_status'), 'user_groups', ['status'], unique=False)
    op.create_index(op.f('ix_user_groups_user_id'), 'user_groups', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_groups_uuid'), 'user_groups', ['uuid'], unique=True)
    op.create_table('products',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('images', sa.JSON(), nullable=True),
    sa.Column('prix_vente', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('prix_achat', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('alert_central', sa.Integer(), nullable=False),
    sa.Column('category_product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_product_id'], ['category_products.id'], name=op.f('fk_products_category_product_id_category_products'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_products_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_category_product_id'), 'products', ['category_product_id'], unique=False)
    op.create_index(op.f('ix_products_deleted_at'), 'products', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_products_name'), 'products', ['name'], unique=False)
    op.create_index(op.f('ix_products_slug'), 'products', ['slug'], unique=True)
    op.create_index(op.f('ix_products_status'), 'products', ['status'], unique=False)
    op.create_index(op.f('ix_products_uuid'), 'products', ['uuid'], unique=True)
    op.create_table('stores',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('devise', sa.String(length=10), nullable=False),
    sa.Column('gerant_id', sa.BigInteger(), nullable=True),
    sa.Column('category_store_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_store_id'], ['category_stores.id'], name=op.f('fk_stores_category_store_id_category_stores'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stores_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['gerant_id'], ['users.id'], name=op.f('fk_stores_gerant_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores'))
    )
    op.create_index(op.f('ix_stores_category_store_id'), 'stores', ['category_store_id'], unique=False)
    op.create_index(op.f('ix_stores_deleted_at'), 'stores', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stores_gerant_id'), 'stores', ['gerant_id'], unique=False)
    op.create_index(op.f('ix_stores_name'), 'stores', ['name'], unique=False)
    op.create_index(op.f('ix_stores_slug'), 'stores', ['slug'], unique=True)
    op.create_index(op.f('ix_stores_status'), 'stores', ['status'], unique=False)
    op.create_index(op.f('ix_stores_uuid'), 'stores', ['uuid'], unique=True)
    op.create_table('cash_sessions',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('opened_by', sa.BigInteger(), nullable=True),
    sa.Column('closed_by', sa.BigInteger(), nullable=True),
    sa.Column('opening_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('expected_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('difference_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.Enum('ouverte', 'fermee', name='cashsessionstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], name=op.f('fk_cash_sessions_closed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['opened_by'], ['users.id'], name=op.f('fk_cash_sessions_opened_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_cash_sessions_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_sessions'))
    )
    op.create_index(op.f('ix_cash_sessions_status'), 'cash_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_cash_sessions_store_id'), 'cash_sessions', ['store_id'], unique=False)
    op.create_index(op.f('ix_cash_sessions_uuid'), 'cash_sessions', ['uuid'], unique=True)
    op.create_table('clients',
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_clients_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_clients_store_id_stores'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clients'))
    )
    op.create_index(op.f('ix_clients_deleted_at'), 'clients', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_index(op.f('ix_clients_phone'), 'clients', ['phone'], unique=False)
    op.create_index(op.f('ix_clients_status'), 'clients', ['status'], unique=False)
    op.create_index(op.f('ix_clients_store_id'), 'clients', ['store_id'], unique=False)
    op.create_index(op.f('ix_clients_uuid'), 'clients', ['uuid'], unique=True)
    op.create_table('commandes',
    sa.Column('boutique_id', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('validated_by', sa.BigInteger(), nullable=True),
    sa.Column('statut', sa.Enum('brouillon', 'en_attente', 'validee', 'rejetee', 'en_preparation', 'livree', 'annulee', name='commandestatut', native_enum=False, length=20), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['stores.id'], name=op.f('fk_commandes_boutique_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_commandes_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], name=op.f('fk_commandes_validated_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commandes'))
    )
    op.create_index(op.f('ix_commandes_boutique_id'), 'commandes', ['boutique_id'], unique=False)
    op.create_index(op.f('ix_commandes_deleted_at'), 'commandes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_commandes_status'), 'commandes', ['status'], unique=False)
    op.create_index(op.f('ix_commandes_statut'), 'commandes', ['statut'], unique=False)
    op.create_index(op.f('ix_commandes_uuid'), 'commandes', ['uuid'], unique=True)
    op.create_table('expenses',
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_mode', sa.Enum('especes', 'mobile_money', 'carte', 'virement', 'cheque', name='paiementmode', native_enum=False, length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['expense_categories.id'], name=op.f('fk_expenses_category_id_expense_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_expenses_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_expenses_store_id_stores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_expenses'))
    )
    op.create_index(op.f('ix_expenses_category_id'), 'expenses', ['category_id'], unique=False)
    op.create_index(op.f('ix_expenses_deleted_at'), 'expenses', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_expenses_status'), 'expenses', ['status'], unique=False)
    op.create_index(op.f('ix_expenses_store_id'), 'expenses', ['store_id'], unique=False)
    op.create_index(op.f('ix_expenses_uuid'), 'expenses', ['uuid'], unique=True)
    op.create_table('purchase_lines',
    sa.Column('purchase_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_ligne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_purchase_lines_product_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], name=op.f('fk_purchase_lines_purchase_id_purchases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_lines'))
    )
    op.create_index(op.f('ix_purchase_lines_deleted_at'), 'purchase_lines', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_purchase_lines_product_id'), 'purchase_lines', ['product_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_purchase_id'), 'purchase_lines', ['purchase_id'], unique=False)
    op.create_index(op.f('ix_purchase_lines_status'), 'purchase_lines', ['status'], unique=False)
    op.create_index(op.f('ix_purchase_lines_uuid'), 'purchase_lines', ['uuid'], unique=True)
    op.create_table('stock_boutique',
    sa.Column('boutique_id', sa.BigInteger(), nullable=False),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('seuil_alert', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['stores.id'], name=op.f('fk_stock_boutique_boutique_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_boutique_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_boutique'))
    )
    op.create_index(op.f('ix_stock_boutique_boutique_id'), 'stock_boutique', ['boutique_id'], unique=False)
    op.create_index(op.f('ix_stock_boutique_deleted_at'), 'stock_boutique', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stock_boutique_product_id'), 'stock_boutique', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_boutique_status'), 'stock_boutique', ['status'], unique=False)
    op.create_index(op.f('ix_stock_boutique_uuid'), 'stock_boutique', ['uuid'], unique=True)
    op.create_table('stock_central',
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('seuil_alert', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_central_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_central'))
    )
    op.create_index(op.f('ix_stock_central_deleted_at'), 'stock_central', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_stock_central_product_id'), 'stock_central', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_central_status'), 'stock_central', ['status'], unique=False)
    op.create_index(op.f('ix_stock_central_uuid'), 'stock_central', ['uuid'], unique=True)
    op.create_table('stock_movements',
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=False),
    sa.Column('source_type', sa.Enum('CENTRAL', 'STORE', 'CLIENT', 'FOURNISSEUR', name='stocklocationtype', native_enum=False, length=20), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('destination_type', sa.Enum('CENTRAL', 'STORE', 'CLIENT', 'FOURNISSEUR', name='stocklocationtype', native_enum=False, length=20), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Enum('ACHAT', 'LIVRAISON', 'VENTE', 'RETOUR_CLIENT', 'RETOUR_FOURNISSEUR', 'TRANSFERT', 'AJUSTEMENT', 'INVENTAIRE', name='movementtype', native_enum=False, length=30), nullable=False),
    sa.Column('reference_type', sa.Enum('COMMANDE', 'VENTE', 'PURCHASE', 'PAIEMENT', 'CREANCE', 'AJUSTEMENT', 'INVENTAIRE', 'EXPENSE', 'CASH_SESSION', 'PRODUCT', 'STORE', 'USER', name='referencetype', native_enum=False, length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_stock_movements_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stock_movements_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_stock_movements_store_id_stores'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stock_movements'))
    )
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_store_id'), 'stock_movements', ['store_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_uuid'), 'stock_movements', ['uuid'], unique=True)
    op.create_table('store_users',
    sa.Column('store_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_store_users_role_id_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_users_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_store_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_users'))
    )
    op.create_index(op.f('ix_store_users_deleted_at'), 'store_users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_store_users_role_id'), 'store_users', ['role_id'], unique=False)
    op.create_index(op.f('ix_store_users_status'), 'store_users', ['status'], unique=False)
    op.create_index(op.f('ix_store_users_store_id'), 'store_users', ['store_id'], unique=False)
    op.create_index(op.f('ix_store_users_user_id'), 'store_users', ['user_id'], unique=False)
    op.create_index(op.f('ix_store_users_uuid'), 'store_users', ['uuid'], unique=True)
    op.create_table('user_permissions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('store_id', sa.BigInteger(), nullable=True),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_user_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_user_permissions_store_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_permissions'))
    )
    op.create_index(op.f('ix_user_permissions_deleted_at'), 'user_permissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_permissions_permission_id'), 'user_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_status'), 'user_permissions', ['status'], unique=False)
    op.create_index(op.f('ix_user_permissions_store_id'), 'user_permissions', ['store_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_user_id'), 'user_permissions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_permissions_uuid'), 'user_permissions', ['uuid'], unique=True)
    op.create_table('cash_movements',
    sa.Column('cash_session_id', sa.BigInteger(), nullable=False),
    sa.Column('type', sa.Enum('entree', 'sortie', name='cashmovementtype', native_enum=False, length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('reference_type', sa.Enum('COMMANDE', 'VENTE', 'PURCHASE', 'PAIEMENT', 'CREANCE', 'AJUSTEMENT', 'INVENTAIRE', 'EXPENSE', 'CASH_SESSION', 'PRODUCT', 'STORE', 'USER', name='referencetype', native_enum=False, length=30), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], name=op.f('fk_cash_movements_cash_session_id_cash_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_cash_movements_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cash_movements'))
    )
    op.create_index(op.f('ix_cash_movements_cash_session_id'), 'cash_movements', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_cash_movements_uuid'), 'cash_movements', ['uuid'], unique=True)
    op.create_table('commande_lignes',
    sa.Column('commande_id', sa.BigInteger(), nullable=False),
    sa.Column('produit_id', sa.BigInteger(), nullable=False),
    sa.Column('quantite_demandee', sa.Integer(), nullable=False),
    sa.Column('quantite_validee', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_ligne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], name=op.f('fk_commande_lignes_commande_id_commandes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['produit_id'], ['products.id'], name=op.f('fk_commande_lignes_produit_id_products'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commande_lignes'))
    )
    op.create_index(op.f('ix_commande_lignes_commande_id'), 'commande_lignes', ['commande_id'], unique=False)
    op.create_index(op.f('ix_commande_lignes_deleted_at'), 'commande_lignes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_commande_lignes_produit_id'), 'commande_lignes', ['produit_id'], unique=False)
    op.create_index(op.f('ix_commande_lignes_status'), 'commande_lignes', ['status'], unique=False)
    op.create_index(op.f('ix_commande_lignes_uuid'), 'commande_lignes', ['uuid'], unique=True)
    op.create_table('ventes',
    sa.Column('boutique_id', sa.BigInteger(), nullable=False),
    sa.Column('vendeur_id', sa.BigInteger(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=True),
    sa.Column('type_vente', sa.Enum('directe', 'credit', name='ventetype', native_enum=False, length=20), nullable=False),
    sa.Column('montant_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remise', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('statut', sa.Enum('en_cours', 'completee', 'partiellement_payee', 'impayee', 'annulee', 'remboursee', name='ventestatut', native_enum=False, length=25), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['stores.id'], name=op.f('fk_ventes_boutique_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_ventes_client_id_clients'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], name=op.f('fk_ventes_vendeur_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventes'))
    )
    op.create_index(op.f('ix_ventes_boutique_id'), 'ventes', ['boutique_id'], unique=False)
    op.create_index(op.f('ix_ventes_client_id'), 'ventes', ['client_id'], unique=False)
    op.create_index(op.f('ix_ventes_deleted_at'), 'ventes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_ventes_status'), 'ventes', ['status'], unique=False)
    op.create_index(op.f('ix_ventes_statut'), 'ventes', ['statut'], unique=False)
    op.create_index(op.f('ix_ventes_uuid'), 'ventes', ['uuid'], unique=True)
    op.create_index(op.f('ix_ventes_vendeur_id'), 'ventes', ['vendeur_id'], unique=False)
    op.create_table('creances',
    sa.Column('vente_id', sa.BigInteger(), nullable=True),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('boutique_id', sa.BigInteger(), nullable=False),
    sa.Column('montant_initial', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('montant_restant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('statut', sa.Enum('active', 'partiellement_payee', 'soldee', 'en_retard', 'annulee', name='creancestatut', native_enum=False, length=25), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['stores.id'], name=op.f('fk_creances_boutique_id_stores'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('fk_creances_client_id_clients'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], name=op.f('fk_creances_vente_id_ventes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_creances'))
    )
    op.create_index(op.f('ix_creances_boutique_id'), 'creances', ['boutique_id'], unique=False)
    op.create_index(op.f('ix_creances_client_id'), 'creances', ['client_id'], unique=False)
    op.create_index(op.f('ix_creances_date_echeance'), 'creances', ['date_echeance'], unique=False)
    op.create_index(op.f('ix_creances_deleted_at'), 'creances', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_creances_status'), 'creances', ['status'], unique=False)
    op.create_index(op.f('ix_creances_statut'), 'creances', ['statut'], unique=False)
    op.create_index(op.f('ix_creances_uuid'), 'creances', ['uuid'], unique=True)
    op.create_index(op.f('ix_creances_vente_id'), 'creances', ['vente_id'], unique=False)
    op.create_table('vente_lignes',
    sa.Column('vente_id', sa.BigInteger(), nullable=False),
    sa.Column('produit_id', sa.BigInteger(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('remise', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_ligne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produit_id'], ['products.id'], name=op.f('fk_vente_lignes_produit_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], name=op.f('fk_vente_lignes_vente_id_ventes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vente_lignes'))
    )
    op.create_index(op.f('ix_vente_lignes_deleted_at'), 'vente_lignes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vente_lignes_produit_id'), 'vente_lignes', ['produit_id'], unique=False)
    op.create_index(op.f('ix_vente_lignes_status'), 'vente_lignes', ['status'], unique=False)
    op.create_index(op.f('ix_vente_lignes_uuid'), 'vente_lignes', ['uuid'], unique=True)
    op.create_index(op.f('ix_vente_lignes_vente_id'), 'vente_lignes', ['vente_id'], unique=False)
    op.create_table('paiements',
    sa.Column('vente_id', sa.BigInteger(), nullable=True),
    sa.Column('creance_id', sa.BigInteger(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('especes', 'mobile_money', 'carte', 'virement', 'cheque', name='paiementmode', native_enum=False, length=20), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creance_id'], ['creances.id'], name=op.f('fk_paiements_creance_id_creances'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], name=op.f('fk_paiements_vente_id_ventes'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paiements'))
    )
    op.create_index(op.f('ix_paiements_creance_id'), 'paiements', ['creance_id'], unique=False)
    op.create_index(op.f('ix_paiements_deleted_at'), 'paiements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_paiements_status'), 'paiements', ['status'], unique=False)
    op.create_index(op.f('ix_paiements_uuid'), 'paiements', ['uuid'], unique=True)
    op.create_index(op.f('ix_paiements_vente_id'), 'paiements', ['vente_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paiements_vente_id'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_uuid'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_status'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_deleted_at'), table_name='paiements')
    op.drop_index(op.f('ix_paiements_creance_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_vente_lignes_vente_id'), table_name='vente_lignes')
    op.drop_index(op.f('ix_vente_lignes_uuid'), table_name='vente_lignes')
    op.drop_index(op.f('ix_vente_lignes_status'), table_name='vente_lignes')
    op.drop_index(op.f('ix_vente_lignes_produit_id'), table_name='vente_lignes')
    op.drop_index(op.f('ix_vente_lignes_deleted_at'), table_name='vente_lignes')
    op.drop_table('vente_lignes')
    op.drop_index(op.f('ix_creances_vente_id'), table_name='creances')
    op.drop_index(op.f('ix_creances_uuid'), table_name='creances')
    op.drop_index(op.f('ix_creances_statut'), table_name='creances')
    op.drop_index(op.f('ix_creances_status'), table_name='creances')
    op.drop_index(op.f('ix_creances_deleted_at'), table_name='creances')
    op.drop_index(op.f('ix_creances_date_echeance'), table_name='creances')
    op.drop_index(op.f('ix_creances_client_id'), table_name='creances')
    op.drop_index(op.f('ix_creances_boutique_id'), table_name='creances')
    op.drop_table('creances')
    op.drop_index(op.f('ix_ventes_vendeur_id'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_uuid'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_statut'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_status'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_deleted_at'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_client_id'), table_name='ventes')
    op.drop_index(op.f('ix_ventes_boutique_id'), table_name='ventes')
    op.drop_table('ventes')
    op.drop_index(op.f('ix_commande_lignes_uuid'), table_name='commande_lignes')
    op.drop_index(op.f('ix_commande_lignes_status'), table_name='commande_lignes')
    op.drop_index(op.f('ix_commande_lignes_produit_id'), table_name='commande_lignes')
    op.drop_index(op.f('ix_commande_lignes_deleted_at'), table_name='commande_lignes')
    op.drop_index(op.f('ix_commande_lignes_commande_id'), table_name='commande_lignes')
    op.drop_table('commande_lignes')
    op.drop_index(op.f('ix_cash_movements_uuid'), table_name='cash_movements')
    op.drop_index(op.f('ix_cash_movements_cash_session_id'), table_name='cash_movements')
    op.drop_table('cash_movements')
    op.drop_index(op.f('ix_user_permissions_uuid'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_user_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_store_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_status'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_permission_id'), table_name='user_permissions')
    op.drop_index(op.f('ix_user_permissions_deleted_at'), table_name='user_permissions')
    op.drop_table('user_permissions')
    op.drop_index(op.f('ix_store_users_uuid'), table_name='store_users')
    op.drop_index(op.f('ix_store_users_user_id'), table_name='store_users')
    op.drop_index(op.f('ix_store_users_store_id'), table_name='store_users')
    op.drop_index(op.f('ix_store_users_status'), table_name='store_users')
    op.drop_index(op.f('ix_store_users_role_id'), table_name='store_users')
    op.drop_index(op.f('ix_store_users_deleted_at'), table_name='store_users')
    op.drop_table('store_users')
    op.drop_index(op.f('ix_stock_movements_uuid'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_store_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_stock_central_uuid'), table_name='stock_central')
    op.drop_index(op.f('ix_stock_central_status'), table_name='stock_central')
    op.drop_index(op.f('ix_stock_central_product_id'), table_name='stock_central')
    op.drop_index(op.f('ix_stock_central_deleted_at'), table_name='stock_central')
    op.drop_table('stock_central')
    op.drop_index(op.f('ix_stock_boutique_uuid'), table_name='stock_boutique')
    op.drop_index(op.f('ix_stock_boutique_status'), table_name='stock_boutique')
    op.drop_index(op.f('ix_stock_boutique_product_id'), table_name='stock_boutique')
    op.drop_index(op.f('ix_stock_boutique_deleted_at'), table_name='stock_boutique')
    op.drop_index(op.f('ix_stock_boutique_boutique_id'), table_name='stock_boutique')
    op.drop_table('stock_boutique')
    op.drop_index(op.f('ix_purchase_lines_uuid'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_status'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_purchase_id'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_product_id'), table_name='purchase_lines')
    op.drop_index(op.f('ix_purchase_lines_deleted_at'), table_name='purchase_lines')
    op.drop_table('purchase_lines')
    op.drop_index(op.f('ix_expenses_uuid'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_store_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_status'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_deleted_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_category_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_commandes_uuid'), table_name='commandes')
    op.drop_index(op.f('ix_commandes_statut'), table_name='commandes')
    op.drop_index(op.f('ix_commandes_status'), table_name='commandes')
    op.drop_index(op.f('ix_commandes_deleted_at'), table_name='commandes')
    op.drop_index(op.f('ix_commandes_boutique_id'), table_name='commandes')
    op.drop_table('commandes')
    op.drop_index(op.f('ix_clients_uuid'), table_name='clients')
    op.drop_index(op.f('ix_clients_store_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_status'), table_name='clients')
    op.drop_index(op.f('ix_clients_phone'), table_name='clients')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_deleted_at'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_cash_sessions_uuid'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_store_id'), table_name='cash_sessions')
    op.drop_index(op.f('ix_cash_sessions_status'), table_name='cash_sessions')
    op.drop_table('cash_sessions')
    op.drop_index(op.f('ix_stores_uuid'), table_name='stores')
    op.drop_index(op.f('ix_stores_status'), table_name='stores')
    op.drop_index(op.f('ix_stores_slug'), table_name='stores')
    op.drop_index(op.f('ix_stores_name'), table_name='stores')
    op.drop_index(op.f('ix_stores_gerant_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_deleted_at'), table_name='stores')
    op.drop_index(op.f('ix_stores_category_store_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_products_uuid'), table_name='products')
    op.drop_index(op.f('ix_products_status'), table_name='products')
    op.drop_index(op.f('ix_products_slug'), table_name='products')
    op.drop_index(op.f('ix_products_name'), table_name='products')
    op.drop_index(op.f('ix_products_deleted_at'), table_name='products')
    op.drop_index(op.f('ix_products_category_product_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_user_groups_uuid'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_user_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_status'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_group_id'), table_name='user_groups')
    op.drop_index(op.f('ix_user_groups_deleted_at'), table_name='user_groups')
    op.drop_table('user_groups')
    op.drop_index(op.f('ix_roles_uuid'), table_name='roles')
    op.drop_index(op.f('ix_roles_status'), table_name='roles')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_deleted_at'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_purchases_uuid'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_supplier_id'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_statut'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_status'), table_name='purchases')
    op.drop_index(op.f('ix_purchases_deleted_at'), table_name='purchases')
    op.drop_table('purchases')
    op.drop_index(op.f('ix_notifications_uuid'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_group_permissions_uuid'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_status'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_permission_id'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_group_id'), table_name='group_permissions')
    op.drop_index(op.f('ix_group_permissions_deleted_at'), table_name='group_permissions')
    op.drop_table('group_permissions')
    op.drop_index(op.f('ix_category_stores_uuid'), table_name='category_stores')
    op.drop_index(op.f('ix_category_stores_status'), table_name='category_stores')
    op.drop_index(op.f('ix_category_stores_slug'), table_name='category_stores')
    op.drop_index(op.f('ix_category_stores_deleted_at'), table_name='category_stores')
    op.drop_table('category_stores')
    op.drop_index(op.f('ix_category_products_uuid'), table_name='category_products')
    op.drop_index(op.f('ix_category_products_status'), table_name='category_products')
    op.drop_index(op.f('ix_category_products_slug'), table_name='category_products')
    op.drop_index(op.f('ix_category_products_deleted_at'), table_name='category_products')
    op.drop_table('category_products')
    op.drop_index(op.f('ix_attachments_uuid'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_reference_type'), table_name='attachments')
    op.drop_index(op.f('ix_attachments_reference_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_activity_logs_uuid'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_user_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_module'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.drop_index(op.f('ix_users_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_uuid'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_deleted_at'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_settings_uuid'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.drop_index(op.f('ix_settings_group_name'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_permissions_uuid'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_status'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_slug'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_deleted_at'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_groups_uuid'), table_name='groups')
    op.drop_index(op.f('ix_groups_status'), table_name='groups')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_index(op.f('ix_groups_deleted_at'), table_name='groups')
    op.drop_table('groups')
    op.drop_index(op.f('ix_expense_categories_uuid'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_status'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_slug'), table_name='expense_categories')
    op.drop_index(op.f('ix_expense_categories_deleted_at'), table_name='expense_categories')
    op.drop_table('expense_categories')
    # ### end Alembic commands ###
