"""add_notes_to_stock_movements

Revision ID: e568baa6fa82
Revises: 8dd441d90d4b
Create Date: 2026-06-26 10:19:20.601824
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e568baa6fa82'
down_revision: str | None = '8dd441d90d4b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_movements', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock_movements', 'notes')
    # ### end Alembic commands ###
