"""vente_retours_remboursements

Revision ID: bd45949311cf
Revises: c1d2e3f4a5b6
Create Date: 2026-07-01 14:20:27.025833
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'bd45949311cf'
down_revision: str | None = 'c1d2e3f4a5b6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vente_retours',
    sa.Column('vente_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vendeur_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('motif', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('total_retourne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], name=op.f('fk_vente_retours_vendeur_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], name=op.f('fk_vente_retours_vente_id_ventes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vente_retours'))
    )
    op.create_index(op.f('ix_vente_retours_deleted_at'), 'vente_retours', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vente_retours_status'), 'vente_retours', ['status'], unique=False)
    op.create_index(op.f('ix_vente_retours_uuid'), 'vente_retours', ['uuid'], unique=True)
    op.create_index(op.f('ix_vente_retours_vente_id'), 'vente_retours', ['vente_id'], unique=False)
    op.create_table('vente_remboursements',
    sa.Column('vente_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('retour_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('vendeur_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=True),
    sa.Column('montant', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('mode', sa.Enum('especes', 'mobile_money', 'carte', 'virement', 'cheque', name='paiementmode', native_enum=False, length=20), nullable=False),
    sa.Column('reference', sa.String(length=200), nullable=True),
    sa.Column('motif', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'archived', name='recordstatus', native_enum=False, length=20), nullable=False),
    sa.Column('infos', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['retour_id'], ['vente_retours.id'], name=op.f('fk_vente_remboursements_retour_id_vente_retours'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendeur_id'], ['users.id'], name=op.f('fk_vente_remboursements_vendeur_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vente_id'], ['ventes.id'], name=op.f('fk_vente_remboursements_vente_id_ventes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vente_remboursements'))
    )
    op.create_index(op.f('ix_vente_remboursements_deleted_at'), 'vente_remboursements', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vente_remboursements_status'), 'vente_remboursements', ['status'], unique=False)
    op.create_index(op.f('ix_vente_remboursements_uuid'), 'vente_remboursements', ['uuid'], unique=True)
    op.create_index(op.f('ix_vente_remboursements_vente_id'), 'vente_remboursements', ['vente_id'], unique=False)
    op.create_table('vente_retour_lignes',
    sa.Column('retour_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('vente_ligne_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('produit_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.Column('prix_unitaire', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_ligne', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['produit_id'], ['products.id'], name=op.f('fk_vente_retour_lignes_produit_id_products'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['retour_id'], ['vente_retours.id'], name=op.f('fk_vente_retour_lignes_retour_id_vente_retours'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vente_ligne_id'], ['vente_lignes.id'], name=op.f('fk_vente_retour_lignes_vente_ligne_id_vente_lignes'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vente_retour_lignes'))
    )
    op.create_index(op.f('ix_vente_retour_lignes_retour_id'), 'vente_retour_lignes', ['retour_id'], unique=False)
    op.create_index(op.f('ix_vente_retour_lignes_uuid'), 'vente_retour_lignes', ['uuid'], unique=True)
    op.drop_index(op.f('ix_clients_type_client'), table_name='clients')
    op.drop_index(op.f('uq_clients_code_client'), table_name='clients')
    op.drop_index(op.f('uq_clients_email'), table_name='clients')
    op.drop_index(op.f('ix_clients_code_client'), table_name='clients')
    op.create_index(op.f('ix_clients_code_client'), 'clients', ['code_client'], unique=True)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.drop_index(op.f('uq_product_stocks_uuid'), table_name='product_stocks')
    op.drop_index(op.f('uq_products_barcode'), table_name='products')
    op.drop_index(op.f('uq_products_sku'), table_name='products')
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=True)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=True)
    op.drop_index(op.f('uq_stock_alert_logs_uuid'), table_name='stock_alert_logs')
    op.drop_index(op.f('uq_stock_locations_uuid'), table_name='stock_locations')
    op.alter_column('stock_movements', 'movement_type',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype', native_enum=False, length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_stock_movements_from_location_id'), 'stock_movements', ['from_location_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_to_location_id'), 'stock_movements', ['to_location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_to_location_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_from_location_id'), table_name='stock_movements')
    op.alter_column('stock_movements', 'movement_type',
               existing_type=sa.Enum('IN', 'OUT', 'TRANSFER', 'ADJUSTMENT', name='movementtype', native_enum=False, length=20),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=False)
    op.create_index(op.f('uq_stock_locations_uuid'), 'stock_locations', ['uuid'], unique=True)
    op.create_index(op.f('uq_stock_alert_logs_uuid'), 'stock_alert_logs', ['uuid'], unique=True)
    op.drop_index(op.f('ix_products_sku'), table_name='products')
    op.create_index(op.f('ix_products_sku'), 'products', ['sku'], unique=False)
    op.drop_index(op.f('ix_products_barcode'), table_name='products')
    op.create_index(op.f('ix_products_barcode'), 'products', ['barcode'], unique=False)
    op.create_index(op.f('uq_products_sku'), 'products', ['sku'], unique=True)
    op.create_index(op.f('uq_products_barcode'), 'products', ['barcode'], unique=True)
    op.create_index(op.f('uq_product_stocks_uuid'), 'product_stocks', ['uuid'], unique=True)
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.drop_index(op.f('ix_clients_code_client'), table_name='clients')
    op.create_index(op.f('ix_clients_code_client'), 'clients', ['code_client'], unique=False)
    op.create_index(op.f('uq_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('uq_clients_code_client'), 'clients', ['code_client'], unique=True)
    op.create_index(op.f('ix_clients_type_client'), 'clients', ['type_client'], unique=False)
    op.drop_index(op.f('ix_vente_retour_lignes_uuid'), table_name='vente_retour_lignes')
    op.drop_index(op.f('ix_vente_retour_lignes_retour_id'), table_name='vente_retour_lignes')
    op.drop_table('vente_retour_lignes')
    op.drop_index(op.f('ix_vente_remboursements_vente_id'), table_name='vente_remboursements')
    op.drop_index(op.f('ix_vente_remboursements_uuid'), table_name='vente_remboursements')
    op.drop_index(op.f('ix_vente_remboursements_status'), table_name='vente_remboursements')
    op.drop_index(op.f('ix_vente_remboursements_deleted_at'), table_name='vente_remboursements')
    op.drop_table('vente_remboursements')
    op.drop_index(op.f('ix_vente_retours_vente_id'), table_name='vente_retours')
    op.drop_index(op.f('ix_vente_retours_uuid'), table_name='vente_retours')
    op.drop_index(op.f('ix_vente_retours_status'), table_name='vente_retours')
    op.drop_index(op.f('ix_vente_retours_deleted_at'), table_name='vente_retours')
    op.drop_table('vente_retours')
    # ### end Alembic commands ###
